seed: 42
num_gpus: 1
trainer:
  name: experiments.autoencoder.AutoencoderTrainer
  train_epochs: 100
  check_val_every_n_epoch: 10
  debug: False
  enable_progress_bar: True
  tabulate_model: True
  seed_eval: 0
  log_grad_norm: False
  logger:
    log_dir: None
    base_log_dir: checkpoints/
    tool: TensorBoard
    stderrthreshold: warning
  callbacks:
    ModelCheckpoint:
      monitor: val/loss
      mode: min
      save_top_k: 1
      save_optimizer_state: False
    LearningRateMonitor:
      every_n_epochs: 1
    ReconstructionCallback:
      class_name: experiments.autoencoder.ReconstructionCallback
      every_n_epochs: 10
      n_samples: 8
model:
  name: models.Autoencoder
  hparams:
    encoder_config:
      name: models.SimpleEncoder
      hparams:
        c_hid: 64
        latent_dim: 128
        act_fn: gelu
        batch_norm: False
    decoder_config:
      name: models.SimpleDecoder
      hparams:
        c_hid: 64
        latent_dim: 128
        act_fn: gelu
        batch_norm: False
        max_img_size: 32
optimizer:
  name: adam
  lr: 1e-3
  transforms:
    weight_decay: 0
    gradient_clip_norm: 10.0
  scheduler:
    name: warmup_cosine_decay
    warmup_steps: 100
dataset:
  constructor: datasets.build_cifar100_datasets
  data_dir: data/
  batch_size: 128
  num_workers: 4
